In [1]:
import numpy as np
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
np.insert(a,1,50)

array([ 1, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.insert(a,1,50.5)

array([ 1, 50,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.insert(a,(1,3,7),50)

array([ 1, 50,  2,  3, 50,  4,  5,  6,  7, 50,  8,  9, 10])

In [7]:
np.delete(a,2)

array([ 1,  2,  4,  5,  6,  7,  8,  9, 10])

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])